### ISSUE TITLE
Slow event emitter

### ISSUE THREAD

**Issue by FedorLap2006** [kislball/goocord#1]
Since event emitter uses `reflect.Value`, it would be really slow. Using `reflect` is a good idea, but it's bad for performance. To solve this problem you can go with code generation (see how it was made in DiscordGo). Also you can remove `reflect.Value` as whole by just using standardized function signature and just use a handler taking `interface{}` as argument and performing switch to determine which function to call

**Comment by kislball** [comment]
This should be resolved by 470fb11.
